// <auto-generated />
using System;
using CdcMonitoring.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CdcMonitoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CdcMonitoringDbContext))]
    [Migration("20260914141617_AddTableAndColumnComments")]
    partial class AddTableAndColumnComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.AlertEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Alarm kaydının birincil anahtarı.");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasComment("İlgili PgConnection.Id (bağlantı düzeyinde alarmlarda dolu).");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Kullanıcıya gösterilen/e-postaya yazılan alarm mesajı.");

                    b.Property<DateTimeOffset?>("NotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("E-posta bildiriminin gönderildiği zaman; null ise henüz bildirilmedi.");

                    b.Property<Guid?>("RelationshipId")
                        .HasColumnType("uuid")
                        .HasComment("İlgili CdcRelationship.Id (ilişki düzeyinde alarmlarda dolu).");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Sorunun düzeldiği zaman; null ise alarm hâlâ aktiftir.");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Önem derecesi: Info, Warning, Critical.");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Alarmın ilk tetiklendiği zaman.");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasComment("Alarm türü: SlotInactive, WalCritical, SubscriptionError, LagWarning, HealthCheckFailed, ReconciliationMismatch.");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "RelationshipId", "ResolvedAt");

                    b.ToTable("AlertEvents", t =>
                        {
                            t.HasComment("Eşik aşımlarında açılan alarm kayıtları; anti-flap mantığıyla aynı aktif sorun için tekrar bildirim göndermez, durum düzelince ResolvedAt ile otomatik kapanır.");
                        });
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Denetim kaydının birincil anahtarı.");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Yapılan işlem: Created, Updated, Deleted, Confirmed, Rejected.");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Değişikliğin yapıldığı zaman.");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Değişikliği yapan kullanıcı (kimlik doğrulama entegre edilene kadar \"system\").");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasComment("Değişen entity kaydının Id'si.");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Değişen entity'nin türü (ör. PgConnection, CdcRelationship).");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasComment("Değişiklik sonrası değer (JSON), varsa.");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasComment("Değişiklik öncesi değer (JSON), varsa.");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "ChangedAt");

                    b.ToTable("AuditLogs", t =>
                        {
                            t.HasComment("Hangi entity'de kimin ne değiştirdiğinin denetim kaydı; eski/yeni değerler JSON olarak tutulur.");
                        });
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.CdcRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("İlişki kaydının birincil anahtarı.");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Onaylama/reddetme zamanı.");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("İlişkiyi onaylayan/reddeden kullanıcı.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("İlişkinin keşfedildiği/oluşturulduğu zaman.");

                    b.Property<string>("PublicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Kaynak veritabanındaki pg_publication adı.");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Kaynak veritabanındaki pg_replication_slots slot adı.");

                    b.Property<Guid>("SourceConnectionId")
                        .HasColumnType("uuid")
                        .HasComment("Kaynak PgConnection.Id (publication tarafı).");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("İlişkinin doğrulanma durumu: Inferred=otomatik keşfedildi (henüz onaylanmadı), Confirmed=kullanıcı onayladı, Manual=elle tanımlandı, Rejected=kullanıcı reddetti (izlemeye dahil edilmez).");

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Hedef veritabanındaki pg_subscription adı.");

                    b.Property<Guid>("TargetConnectionId")
                        .HasColumnType("uuid")
                        .HasComment("Hedef PgConnection.Id (subscription tarafı).");

                    b.HasKey("Id");

                    b.HasIndex("TargetConnectionId");

                    b.HasIndex("SourceConnectionId", "TargetConnectionId", "SlotName")
                        .IsUnique();

                    b.ToTable("CdcRelationships", t =>
                        {
                            t.HasComment("Kaynak ve hedef PgConnection arasındaki CDC ilişkisi (publication/subscription/replication slot üçlüsü); pg_publication, pg_subscription, pg_replication_slots sistem görünümleri salt-okuma taranarak otomatik keşfedilir ya da elle tanımlanır.");
                        });
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.CdcRelationshipHealth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Sağlık kaydının birincil anahtarı.");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Bu anlık görüntünün alındığı zaman.");

                    b.Property<long?>("LagBytes")
                        .HasColumnType("bigint")
                        .HasComment("Kaynak-hedef arasındaki replikasyon gecikmesi, byte cinsinden.");

                    b.Property<DateTimeOffset?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Subscription'ın en son başarılı senkronizasyon zamanı.");

                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("uuid")
                        .HasComment("Bağlı olduğu CdcRelationship.Id.");

                    b.Property<bool>("SlotActive")
                        .HasColumnType("boolean")
                        .HasComment("pg_replication_slots.active değeri; slot'un o an aktif olup olmadığı.");

                    b.Property<string>("SubscriptionState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Subscription durumu: Enabled=çalışıyor, Disabled=devre dışı, Error=hata veriyor, Unknown=okunamadı.");

                    b.Property<string>("WalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("pg_replication_slots.wal_status değeri (ör. reserved, extended, lost).");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAt");

                    b.HasIndex("RelationshipId", "CheckedAt");

                    b.ToTable("CdcRelationshipHealthEntries", t =>
                        {
                            t.HasComment("Bir CdcRelationship için periyodik sağlık anlık görüntüsü (slot aktifliği, WAL durumu, lag, subscription durumu). Topoloji ekranındaki kenar renklerinin ve slot/lag/subscription alarmlarının kaynağıdır.");
                        });
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.ConnectionHealthCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Kontrol kaydının birincil anahtarı.");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Kontrolün yapıldığı zaman.");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid")
                        .HasComment("Kontrol edilen PgConnection.Id.");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("Bağlantı başarısızsa alınan hata mesajı.");

                    b.Property<bool>("IsUp")
                        .HasColumnType("boolean")
                        .HasComment("Bağlantının o an kurulabilip kurulamadığı.");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("double precision")
                        .HasComment("Bağlantı kurma gecikmesi, milisaniye cinsinden (başarısızsa null).");

                    b.Property<string>("PostgresVersion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Sunucudan okunan PostgreSQL sürüm bilgisi (SELECT version()).");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "CheckedAt");

                    b.ToTable("ConnectionHealthChecks", t =>
                        {
                            t.HasComment("Bir PgConnection'ın periyodik erişilebilirlik kontrolü (up/down, gecikme, Postgres versiyonu). Ardışık başarısızlık sayısı HealthCheckFailed alarmını besler.");
                        });
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.JobSchedule", b =>
                {
                    b.Property<string>("JobName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Job'un benzersiz adı (birincil anahtar); CdcMonitoring.Infrastructure.Jobs.JobNames sabitlerinden biri.");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Job'un en son başarıyla tamamlandığı zaman; null ise hiç çalışmamıştır.");

                    b.HasKey("JobName");

                    b.ToTable("JobSchedules", t =>
                        {
                            t.HasComment("Çok replikalı dağıtımda hangi arka plan job'unun ne zaman çalıştığını izleyen 'claim' tablosu; atomik güncelleme ile aynı job'un iki replikada aynı anda çalışması engellenir (bkz. IJobScheduleRepository.TryClaimAsync).");
                        });

                    b.HasData(
                        new
                        {
                            JobName = "connection-health-check"
                        },
                        new
                        {
                            JobName = "cdc-discovery"
                        },
                        new
                        {
                            JobName = "alert-evaluation"
                        },
                        new
                        {
                            JobName = "weekly-reconciliation"
                        },
                        new
                        {
                            JobName = "retention-cleanup"
                        });
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.PgConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Bağlantı kaydının birincil anahtarı.");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Kaydın oluşturulma zamanı.");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Kaydı oluşturan kullanıcı.");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Bağlanılacak veritabanı adı.");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("Bağlantı hakkında serbest metin açıklama.");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("ASP.NET Core Data Protection ile şifrelenmiş parola; hiçbir ekranda çözülmüş haliyle geri gösterilmez.");

                    b.Property<string>("EnvironmentTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Ortam etiketi (ör. Prod/Test/Dev); UI'da ve topoloji grafiğinde gösterilir.");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("PostgreSQL sunucusunun host adresi.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("false ise bağlantı health check/discovery döngülerine dahil edilmez.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Bağlantıya verilen görünen ad.");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasComment("PostgreSQL sunucusunun port numarası (varsayılan 5432).");

                    b.Property<string>("SslMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Npgsql SSL modu: Disable/Allow/Prefer/Require/VerifyCA/VerifyFull.");

                    b.Property<bool>("TrustServerCertificate")
                        .HasColumnType("boolean")
                        .HasComment("Yalnızca SslMode=Require ile anlamlı; kendi-imzalı sertifikalı iç ağ PostgreSQL örnekleri için sunucu sertifikası doğrulamasını atlar (VerifyCA/VerifyFull bu bayraktan etkilenmez, her koşulda doğrulama yapar).");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Kaydın son güncellenme zamanı (yoksa hiç güncellenmemiştir).");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Kaydı son güncelleyen kullanıcı.");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Bağlantı için kullanılan PostgreSQL kullanıcı adı.");

                    b.HasKey("Id");

                    b.HasIndex("Host", "Port", "DatabaseName")
                        .IsUnique();

                    b.ToTable("PgConnections", t =>
                        {
                            t.HasComment("İzlenen PostgreSQL sunucularının kayıt defteri. Uygulama buradaki bağlantılara karşı salt-okuma çalışır; publication/subscription/replication slot asla oluşturmaz, değiştirmez veya silmez.");
                        });
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.ReconciliationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Kontrol sonucunun birincil anahtarı.");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("Tutarsızlık varsa ayrıntı metni (ör. fark eden satır/kolon bilgisi).");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("boolean")
                        .HasComment("Satır sayısı ve checksum'ların eşleşip eşleşmediği.");

                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("uuid")
                        .HasComment("Bağlı olduğu CdcRelationship.Id.");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Kontrolün çalıştırıldığı zaman.");

                    b.Property<string>("SourceChecksum")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Kaynak tablonun yayınlanan kolonlar üzerinden hesaplanan checksum'ı.");

                    b.Property<long?>("SourceRowCount")
                        .HasColumnType("bigint")
                        .HasComment("Kaynak tablodaki satır sayısı.");

                    b.Property<string>("TargetChecksum")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Hedef tablonun aynı kolonlar üzerinden hesaplanan checksum'ı.");

                    b.Property<long?>("TargetRowCount")
                        .HasColumnType("bigint")
                        .HasComment("Hedef tablodaki satır sayısı.");

                    b.HasKey("Id");

                    b.HasIndex("RunAt");

                    b.HasIndex("RelationshipId", "RunAt");

                    b.ToTable("ReconciliationResults", t =>
                        {
                            t.HasComment("Onaylanmış CdcRelationship'ler için Veri Tutarlılık Kontrolü sonuçları: kaynak-hedef satır sayısı ve checksum karşılaştırması (checksum yalnızca publication'da yayınlanan kolonları kapsar). ReconciliationRetentionDays süresine göre eski kayıtlar otomatik silinir.");
                        });
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Sabit singleton Id (00000000-0000-0000-0000-000000000001).");

                    b.Property<int>("AlertingIntervalSeconds")
                        .HasColumnType("integer")
                        .HasComment("Alarm değerlendirme (eşik kontrolü) taramaları arasındaki süre (sn).");

                    b.Property<int>("ConsecutiveHealthCheckFailures")
                        .HasColumnType("integer")
                        .HasComment("HealthCheckFailed alarmı üretmek için gereken ardışık başarısız kontrol sayısı.");

                    b.Property<int>("DiscoveryIntervalSeconds")
                        .HasColumnType("integer")
                        .HasComment("CDC ilişki keşif (discovery) taramaları arasındaki süre (sn).");

                    b.Property<int>("DiscoveryMaxDegreeOfParallelism")
                        .HasColumnType("integer")
                        .HasComment("Keşif taramasında eşzamanlı çalışacak bağlantı sayısı.");

                    b.Property<int>("DiscoveryTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasComment("Bir keşif denemesi için zaman aşımı süresi (sn).");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean")
                        .HasComment("E-posta bildirimlerinin açık olup olmadığı.");

                    b.Property<string>("EncryptedSmtpPassword")
                        .HasColumnType("text")
                        .HasComment("Data Protection ile şifrelenmiş SMTP parolası; hiçbir ekranda geri gösterilmez.");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Bildirim e-postalarının gönderen adresi.");

                    b.Property<string>("FromDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Bildirim e-postalarının gönderen görünen adı.");

                    b.Property<int>("HealthCheckIntervalSeconds")
                        .HasColumnType("integer")
                        .HasComment("ConnectionHealthCheck taramaları arasındaki süre (sn).");

                    b.Property<int>("HealthCheckMaxDegreeOfParallelism")
                        .HasColumnType("integer")
                        .HasComment("Health check taramasında eşzamanlı çalışacak bağlantı sayısı.");

                    b.Property<int>("HealthCheckRetentionDays")
                        .HasColumnType("integer")
                        .HasComment("ConnectionHealthCheck kayıtlarının saklanma süresi (gün).");

                    b.Property<int>("HealthCheckTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasComment("Bir health check denemesi için zaman aşımı süresi (sn).");

                    b.Property<string>("HealthyWalStatusesCsv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Sağlıklı sayılan pg_replication_slots.wal_status değerlerinin virgülle ayrılmış listesi (ör. reserved,extended).");

                    b.Property<long>("LagWarningBytes")
                        .HasColumnType("bigint")
                        .HasComment("LagWarning alarmı için byte cinsinden eşik değer.");

                    b.Property<int>("LagWarningSustainedMinutes")
                        .HasColumnType("integer")
                        .HasComment("Lag eşiğinin bu süre boyunca sürekli aşılması LagWarning alarmı üretir (dk).");

                    b.Property<string>("RecipientsCsv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Bildirim e-postalarının alıcı listesi, virgülle ayrılmış.");

                    b.Property<int>("ReconciliationIntervalSeconds")
                        .HasColumnType("integer")
                        .HasComment("Veri Tutarlılık Kontrolü taramaları arasındaki süre (sn).");

                    b.Property<int>("ReconciliationRetentionDays")
                        .HasColumnType("integer")
                        .HasComment("ReconciliationResult kayıtlarının saklanma süresi (gün).");

                    b.Property<int>("SlotInactiveMinutes")
                        .HasColumnType("integer")
                        .HasComment("Bir slot'un bu süre boyunca inaktif kalması SlotInactive alarmı üretir (dk).");

                    b.Property<string>("SmtpHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("SMTP sunucu adresi.");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer")
                        .HasComment("SMTP sunucu portu.");

                    b.Property<bool>("SmtpUseStartTls")
                        .HasColumnType("boolean")
                        .HasComment("SMTP bağlantısında STARTTLS kullanılıp kullanılmayacağı.");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("SMTP kimlik doğrulama kullanıcı adı.");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Ayarların son güncellenme zamanı.");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Ayarları son güncelleyen kullanıcı.");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", t =>
                        {
                            t.HasComment("Tekil (sabit Id'li) ayar satırı: tarama aralıkları, alarm eşikleri, SMTP/e-posta yapılandırması ve saklama süreleri. /settings ekranından yeniden başlatma gerekmeden düzenlenir.");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AlertingIntervalSeconds = 60,
                            ConsecutiveHealthCheckFailures = 2,
                            DiscoveryIntervalSeconds = 60,
                            DiscoveryMaxDegreeOfParallelism = 5,
                            DiscoveryTimeoutSeconds = 10,
                            EmailEnabled = false,
                            FromAddress = "cdc-monitoring@example.com",
                            FromDisplayName = "CDC Monitoring",
                            HealthCheckIntervalSeconds = 30,
                            HealthCheckMaxDegreeOfParallelism = 10,
                            HealthCheckRetentionDays = 7,
                            HealthCheckTimeoutSeconds = 5,
                            HealthyWalStatusesCsv = "reserved,extended",
                            LagWarningBytes = 52428800L,
                            LagWarningSustainedMinutes = 10,
                            RecipientsCsv = "",
                            ReconciliationIntervalSeconds = 604800,
                            ReconciliationRetentionDays = 90,
                            SlotInactiveMinutes = 5,
                            SmtpHost = "",
                            SmtpPort = 587,
                            SmtpUseStartTls = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.CdcRelationship", b =>
                {
                    b.HasOne("CdcMonitoring.Domain.Entities.PgConnection", "SourceConnection")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("SourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CdcMonitoring.Domain.Entities.PgConnection", "TargetConnection")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceConnection");

                    b.Navigation("TargetConnection");
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.CdcRelationshipHealth", b =>
                {
                    b.HasOne("CdcMonitoring.Domain.Entities.CdcRelationship", "Relationship")
                        .WithMany("HealthHistory")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.ConnectionHealthCheck", b =>
                {
                    b.HasOne("CdcMonitoring.Domain.Entities.PgConnection", "Connection")
                        .WithMany("HealthChecks")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.ReconciliationResult", b =>
                {
                    b.HasOne("CdcMonitoring.Domain.Entities.CdcRelationship", "Relationship")
                        .WithMany("ReconciliationResults")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.CdcRelationship", b =>
                {
                    b.Navigation("HealthHistory");

                    b.Navigation("ReconciliationResults");
                });

            modelBuilder.Entity("CdcMonitoring.Domain.Entities.PgConnection", b =>
                {
                    b.Navigation("HealthChecks");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
